# This file is part of pokemontcgsdk.
# https://github.com/PokemonTCG/pokemon-tcg-sdk-python

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Andrew Backes <backes.andrew@gmail.com>

language: python

python:
    - "3.9"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test

after_success:
    - coveralls